branch-defaults:
  default:
    environment: codeblog2-dev
    group_suffix: null
global:
  application_name: codeblog2
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Java 8 running on 64bit Amazon Linux
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application

deploy:
  artifact: target/codeblog-0.0.1-SNAPSHOT.jar